// @ts-nocheck
// TypeScript migration of issue-template-engine.js
// Provides structured issue title/body generation with optional AI enrichment.

interface IssueItem { id: string; message: string; error?: string; severity?: string; }
interface IssueDraft { title: string; body: string; }
interface RuleTemplateFn { (issue: IssueItem, ctx: any): IssueDraft; }

const DEFAULT_SEVERITY_LABELS: Record<string,string> = { error: 'High', warning: 'Medium', info: 'Low', low: 'Low' };

// Placeholder for future rule-specific templates
const RULE_TEMPLATES: Record<string, RuleTemplateFn | RuleTemplateFn> = {};

function serializeMeta(meta:any){
  try { return JSON.stringify(meta, null, 2).replace(/</g, '\\u003c'); } catch { return '{}'; }
}

async function maybeGenerateWithModel(base:IssueDraft, meta:any, ctx:any):Promise<IssueDraft>{
  if(!(window as any).ENABLE_ISSUE_AI) return base;
  if(typeof (window as any).CustomIssueAIProvider === 'function'){
    try {
      const enriched = await (window as any).CustomIssueAIProvider(base, meta, ctx);
      if(enriched && typeof enriched.body === 'string') return enriched;
    } catch(e){ console.warn('[IssueTemplateEngine] AI provider failed, falling back', e); }
  }
  return base;
}

function inferGenericFix(issue:IssueItem){
  const id = issue.id || '';
  if(id.includes('missing-file')) return 'Add the required file with appropriate content.';
  if(id.includes('missing-folder')) return 'Create the required folder structure including necessary files.';
  if(id.includes('missing-workflow')) return 'Add the missing GitHub Actions workflow under `.github/workflows/`.';
  if(id.includes('readme')) return 'Update or create `README.md` with required sections (Overview, Prereqs, Getting Started, Resources).';
  if(id.includes('bicep')) return 'Add or update the Bicep resources so required infrastructure components are declared.';
  if(id.includes('azure-yaml')) return 'Update `azure.yaml` to include environment, services, and infra definitions per guidelines.';
  return 'Review the rule documentation and implement the required changes.';
}

function buildStandardBody(issue:IssueItem, ctx:any, overrides:any = {}):string{
  const severityDisplay = ctx.severityDisplay;
  const lines:string[] = [];
  lines.push(`# ${issue.message}`,'');
  if(overrides.summary){
    lines.push('## Summary','', overrides.summary.trim(), '');
  } else if(issue.error){
    lines.push('## Details','', issue.error.trim(), '');
  }
  lines.push('## Problem','', overrides.problem || 'This repository does not meet one of the required template rules.','');
  lines.push('## Impact','', overrides.impact || 'Leaving this unresolved can reduce template reliability, developer experience, or automation effectiveness.','');
  lines.push('## Recommended Fix','', overrides.fix || inferGenericFix(issue), '');
  if(Array.isArray(overrides.acceptance) && overrides.acceptance.length){
    lines.push('## Acceptance Criteria','');
    overrides.acceptance.forEach((c:string)=> lines.push(`- [ ] ${c}`));
    lines.push('');
  }
  lines.push('## Context','');
  lines.push(`- Rule ID: ${issue.id}`);
  lines.push(`- Severity: ${severityDisplay}`);
  lines.push(`- Rule Set: ${ctx.ruleSetDisplay}${ctx.customGistUrl ? ` (custom from ${ctx.customGistUrl})` : ''}`);
  if(ctx.mainIssue) lines.push(`- Parent Issue: #${ctx.mainIssue.number}`);
  lines.push('');
  const meta = serializeMeta({ ruleId: issue.id, severity: issue.severity || 'warning', severityDisplay, ruleSet: ctx.ruleSet, parentIssueNumber: ctx.mainIssue ? ctx.mainIssue.number : null, analyzerVersion: (window as any).TemplateDoctorVersion || 'unknown', timestamp: Date.now() });
  lines.push('<!-- template-doctor:metadata', meta, '-->','');
  lines.push('*Generated by Template Doctor issue template engine. Adjust the acceptance criteria if you implement an alternative compliant approach.*');
  return lines.join('\n');
}

function resolveRuleTemplate(issue:IssueItem){
  if(RULE_TEMPLATES[issue.id]) return RULE_TEMPLATES[issue.id];
  for(const key of Object.keys(RULE_TEMPLATES)){
    if(key.endsWith('*')){
      const prefix = key.slice(0,-1);
      if(issue.id.startsWith(prefix)) return RULE_TEMPLATES[key];
    }
  }
  return null;
}

async function generateChildIssue(issue:IssueItem, ctx:any):Promise<IssueDraft>{
  const severityRaw = (issue.severity || 'warning').toLowerCase();
  const severityDisplay = DEFAULT_SEVERITY_LABELS[severityRaw] || 'Medium';
  const extendedCtx = { ...ctx, severityDisplay };
  const ruleTemplate:any = resolveRuleTemplate(issue);
  let draft:IssueDraft | undefined;
  if(typeof ruleTemplate === 'function'){
    draft = ruleTemplate(issue, { ...extendedCtx, buildStandardBody: (iss:IssueItem,c:any,o:any)=> buildStandardBody(iss,c,o) });
  }
  if(!draft){
    draft = { title: `${issue.message} [${issue.id}]`, body: buildStandardBody(issue, extendedCtx) };
  }
  draft = await maybeGenerateWithModel(draft, { ruleId: issue.id, severity: severityRaw }, extendedCtx);
  return draft;
}

// Export global (maintain backward compatibility)
(window as any).IssueTemplateEngine = {
  generateChildIssue,
  _inferGenericFix: inferGenericFix,
  _buildStandardBody: buildStandardBody,
  _ruleTemplates: RULE_TEMPLATES
};
